---
title: "HW1"
author: "Ben Gaudiosi"
date: "January 22, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##1. Create the vectors:
###(a)
```{r}
1:20
```
###(b)
```{r}
20:1
```
###(c)
```{r}
c(1:20, 19:1)
```
###(d)
```{r}
tmp <- c(4,6,3)
```
###(e)
```{r}
rep(tmp, times=4)
```
###(f)
```{r}
 c(rep(tmp, times=10),4)
```
###(g)
```{r}
c(rep(4, each=10), rep(6, each=20), rep(3, each=30))
```

##2. 
```{r}
x <- seq(3, 6, by=0.1)
exp(x)*cos(x)
```

##3.
###(a)
```{r}
(0.1^(seq(3,36,by=3)))*(0.2^(seq(1,34,by=3)))
```
###(b)
```{r}
b <- 1:25
(2^b)*(1/b)
```

##4.
###(a)
```{r}
i <- 10:100
sum(i^3 + 4*i^2)
```
###(b)
```{r}
i <- 1:25
sum(((2^i)/i) + ((3^i)/(i^2)))
```

##5.
###(a)
```{r}
paste("label", 1:30, sep=" ")
```
###(b)
```{r}
paste("fn", 1:30, sep="")
```

##6.
```{r}
set.seed(50)
xVec <- sample(0:999, 250, replace=T)
yVec <- sample(0:999, 250, replace=T)
```
###(a)
```{r}
yVec[2:250] - xVec[1:249]
```
###(b)
```{r}
sin(yVec[1:249])/cos(xVec[2:250])
```
###(c)
```{r}
xVec[1:248] + 2*xVec[2:249] - xVec[3:250]
```
###(d)
```{r}
sum(exp(-xVec[1:249] + 1)/(xVec[1:249] + 10))
```

##7.
###(a)
```{r}
yVec[yVec > 600]
```
###(b)
```{r}
which(yVec > 600)
```
###(c)
```{r}
xVec[which(yVec > 600)]
```
###(d)
```{r}
sqrt(abs(xVec - mean(xVec)))
```
###(e)
```{r}
length(yVec[abs(yVec - max(yVec)) <= 200])
```
###(f)
```{r}
length(xVec[xVec %% 2 == 0])
```
###(g)
```{r}
xVec[sort(yVec, decreasing=FALSE, index.return=TRUE)$ix]
```
###(h)
```{r}
yVec[seq(1, 250, by=3)]
```

##8. 
```{r}
sum(cumprod(c(1, seq(2,38,by=2)/seq(3,39,by=2))))
```